export const actionTypes = {
  ToggleDarkMode: 'ToggleDarkMode',
  LOGOUT_USER: 'LOGOUT_USER',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
};
